<a href="https://colab.research.google.com/github/harshavardhangadila/Tensors-Operations/blob/main/Tensor%20Operations%20using%20TensorFlow/TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
!pip install tensorflow


In [24]:
import tensorflow as tf
import numpy as np


In [25]:
# Set seeds for reproducibility
tf.random.set_seed(123)
np.random.seed(123)

In [26]:
# Creating a scalar tensor
scalar = tf.constant(10, dtype=tf.int32)
print("Scalar:", scalar)

# Creating a vector tensor
vector = tf.constant([1.5, 2.5, 3.5], dtype=tf.float32)
print("Vector:", vector)

# Creating a matrix tensor
matrix = tf.constant([[1, 2], [3, 4]], dtype=tf.int32)
print("Matrix:\n", matrix)

Scalar: tf.Tensor(10, shape=(), dtype=int32)
Vector: tf.Tensor([1.5 2.5 3.5], shape=(3,), dtype=float32)
Matrix:
 tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [27]:
# Checking shape of tensor
shape = matrix.shape
print("Shape:", shape)

# Checking datatype of tensor
dtype = matrix.dtype
print("Dtype:", dtype)

# Checking number of dimensions
ndim = matrix.ndim
print("Dimensions:", ndim)

Shape: (2, 2)
Dtype: <dtype: 'int32'>
Dimensions: 2


In [28]:
# Casting tensor type
vector_casted = tf.cast(vector, dtype=tf.float64)
print("Vector Casted:", vector_casted)

# Adding tensors
added_tensor = vector + 2
print("Added Tensor:", added_tensor)

# Multiplying tensors
multiplied_tensor = vector * 3
print("Multiplied Tensor:", multiplied_tensor)

Vector Casted: tf.Tensor([1.5 2.5 3.5], shape=(3,), dtype=float64)
Added Tensor: tf.Tensor([3.5 4.5 5.5], shape=(3,), dtype=float32)
Multiplied Tensor: tf.Tensor([ 4.5  7.5 10.5], shape=(3,), dtype=float32)


In [29]:
# Computing sum of elements
sum_value = tf.reduce_sum(vector)
print("Sum:", sum_value)

Sum: tf.Tensor(7.5, shape=(), dtype=float32)


In [30]:
# Matrix multiplication
mat_A = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
mat_B = tf.constant([[5, 6], [7, 8]], dtype=tf.float32)
mat_mul = tf.matmul(mat_A, mat_B)
print("Matrix Multiplication:\n", mat_mul)


Matrix Multiplication:
 tf.Tensor(
[[19. 22.]
 [43. 50.]], shape=(2, 2), dtype=float32)


In [31]:
# Transposing a matrix
transposed_matrix = tf.transpose(mat_A)
print("Transposed:\n", transposed_matrix)

# Computing Frobenius norm
norm_matrix = tf.norm(mat_A)
print("Frobenius Norm:", norm_matrix)

# Concatenating tensors
concat_tensor = tf.concat([vector, vector], axis=0)
print("Concatenated Tensor:", concat_tensor)

Transposed:
 tf.Tensor(
[[1. 3.]
 [2. 4.]], shape=(2, 2), dtype=float32)
Frobenius Norm: tf.Tensor(5.4772253, shape=(), dtype=float32)
Concatenated Tensor: tf.Tensor([1.5 2.5 3.5 1.5 2.5 3.5], shape=(6,), dtype=float32)


In [32]:
# Stacking tensors
stacked_tensor = tf.stack([vector, vector], axis=1)
print("Stacked Tensor:\n", stacked_tensor)

# Expanding dimensions
expanded_tensor = tf.expand_dims(vector, axis=0)
print("Expanded Tensor:", expanded_tensor)

# Squeezing dimensions
squeezed_tensor = tf.squeeze(expanded_tensor)
print("Squeezed Tensor:", squeezed_tensor)

Stacked Tensor:
 tf.Tensor(
[[1.5 1.5]
 [2.5 2.5]
 [3.5 3.5]], shape=(3, 2), dtype=float32)
Expanded Tensor: tf.Tensor([[1.5 2.5 3.5]], shape=(1, 3), dtype=float32)
Squeezed Tensor: tf.Tensor([1.5 2.5 3.5], shape=(3,), dtype=float32)


In [33]:
# Computing the maximum value in a tensor
max_value = tf.reduce_max(vector)
print("Max Value:", max_value)

# Computing the mean of elements
mean_value = tf.reduce_mean(vector)
print("Mean Value:", mean_value)

# Computing softmax
softmax_values = tf.nn.softmax(vector)
print("Softmax:", softmax_values)


Max Value: tf.Tensor(3.5, shape=(), dtype=float32)
Mean Value: tf.Tensor(2.5, shape=(), dtype=float32)
Softmax: tf.Tensor([0.09003057 0.24472848 0.6652409 ], shape=(3,), dtype=float32)


In [34]:
# Computing determinant of a matrix
determinant = tf.linalg.det(mat_A)
print("Determinant:", determinant)

# Computing matrix inverse
inverse_matrix = tf.linalg.inv(tf.constant([[4.0, 7.0], [2.0, 6.0]]))
print("Inverse Matrix:\n", inverse_matrix)

# Computing matrix trace
trace_matrix = tf.linalg.trace(mat_A)
print("Trace:", trace_matrix)

Determinant: tf.Tensor(-2.0, shape=(), dtype=float32)
Inverse Matrix:
 tf.Tensor(
[[ 0.59999996 -0.69999987]
 [-0.19999997  0.39999995]], shape=(2, 2), dtype=float32)
Trace: tf.Tensor(5.0, shape=(), dtype=float32)


In [35]:
# Computing matrix rank
rank_matrix = tf.rank(mat_A)
print("Rank:", rank_matrix)

# Computing element-wise division
elementwise_div = mat_A / mat_B
print("Element-wise Division:\n", elementwise_div)


Rank: tf.Tensor(2, shape=(), dtype=int32)
Element-wise Division:
 tf.Tensor(
[[0.2        0.33333334]
 [0.42857143 0.5       ]], shape=(2, 2), dtype=float32)


In [36]:
# Computing eigenvalues and eigenvectors
eigvals, eigvecs = tf.linalg.eigh(tf.constant([[6.0, 2.0], [2.0, 3.0]]))
print("Eigenvalues:", eigvals)
print("Eigenvectors:\n", eigvecs)

# Computing Cholesky decomposition
cholesky_decomp = tf.linalg.cholesky(tf.constant([[4.0, 2.0], [2.0, 3.0]]))
print("Cholesky Decomposition:\n", cholesky_decomp)

Eigenvalues: tf.Tensor([1.9999999 7.       ], shape=(2,), dtype=float32)
Eigenvectors:
 tf.Tensor(
[[-0.4472136  0.8944272]
 [ 0.8944272  0.4472136]], shape=(2, 2), dtype=float32)
Cholesky Decomposition:
 tf.Tensor(
[[2.        0.       ]
 [1.        1.4142135]], shape=(2, 2), dtype=float32)


In [37]:
# Performing Singular Value Decomposition (SVD)
s, u, v = tf.linalg.svd(mat_A)
print("Singular Values:", s)
print("U:\n", u)
print("V:\n", v)

# Computing element-wise exponent
exp_tensor = tf.exp(vector)
print("Exponential Tensor:", exp_tensor)

Singular Values: tf.Tensor([5.4649854  0.36596614], shape=(2,), dtype=float32)
U:
 tf.Tensor(
[[-0.40455362 -0.91451436]
 [-0.9145144   0.40455356]], shape=(2, 2), dtype=float32)
V:
 tf.Tensor(
[[-0.5760485   0.81741554]
 [-0.81741554 -0.5760485 ]], shape=(2, 2), dtype=float32)
Exponential Tensor: tf.Tensor([ 4.481689 12.182494 33.11545 ], shape=(3,), dtype=float32)


In [38]:
# Computing element-wise logarithm
log_tensor = tf.math.log(vector)
print("Logarithmic Tensor:", log_tensor)

# Computing cosine similarity
cosine_sim = tf.tensordot(vector, vector, axes=1) / (tf.norm(vector) * tf.norm(vector))
print("Cosine Similarity:", cosine_sim)

# Computing QR decomposition
q, r = tf.linalg.qr(tf.cast(mat_A, tf.float32))
print("Q:\n", q)
print("R:\n", r)

Logarithmic Tensor: tf.Tensor([0.40546513 0.91629076 1.252763  ], shape=(3,), dtype=float32)
Cosine Similarity: tf.Tensor(1.0, shape=(), dtype=float32)
Q:
 tf.Tensor(
[[-0.3162278  -0.9486833 ]
 [-0.9486833   0.31622773]], shape=(2, 2), dtype=float32)
R:
 tf.Tensor(
[[-3.1622777  -4.4271884 ]
 [ 0.         -0.63245535]], shape=(2, 2), dtype=float32)


In [39]:
# Computing log determinant
log_determinant = tf.linalg.logdet(tf.constant([[4.0, 7.0], [2.0, 6.0]]))
print("Log Determinant:", log_determinant)

# Computing batch matrix multiplication
batch_A = tf.random.uniform((2, 3, 3))
batch_B = tf.random.uniform((2, 3, 3))
batch_matmul = tf.matmul(batch_A, batch_B)
print("Batch Matrix Multiplication:\n", batch_matmul)

Log Determinant: tf.Tensor(2.9957323, shape=(), dtype=float32)
Batch Matrix Multiplication:
 tf.Tensor(
[[[0.72927344 0.5716828  0.14404717]
  [1.5717154  1.0248424  0.48348585]
  [1.0944614  0.7570255  0.27985233]]

 [[0.52306616 0.4563491  0.46249467]
  [1.0093877  0.86679745 0.86440766]
  [0.9291225  0.8322909  0.7983096 ]]], shape=(2, 3, 3), dtype=float32)


In [40]:
# Computing element-wise ReLU activation
relu_tensor = tf.nn.relu(tf.constant([-1.0, 2.0, -3.0, 4.0]))
print("ReLU Tensor:", relu_tensor)

# Computing standard deviation of a tensor
std_dev = tf.math.reduce_std(tf.cast(vector, tf.float32))
print("Standard Deviation:", std_dev)

# Computing variance of a tensor
variance = tf.math.reduce_variance(tf.cast(vector, tf.float32))
print("Variance:", variance)

ReLU Tensor: tf.Tensor([0. 2. 0. 4.], shape=(4,), dtype=float32)
Standard Deviation: tf.Tensor(0.81649655, shape=(), dtype=float32)
Variance: tf.Tensor(0.6666667, shape=(), dtype=float32)


In [41]:
# Creating a tensor with normally distributed values
normal_tensor = tf.random.normal((5, 5), mean=0, stddev=1)
print("Normal Tensor:\n", normal_tensor)

# Creating a tensor with a truncated normal distribution
truncated_tensor = tf.random.truncated_normal((5, 5), mean=0, stddev=1)
print("Truncated Normal Tensor:\n", truncated_tensor)

# Computing Hadamard (element-wise) product
hadamard_product = mat_A * mat_B
print("Hadamard Product:\n", hadamard_product)



Normal Tensor:
 tf.Tensor(
[[-0.61346    -1.0256169  -1.1752816  -0.79817134  0.31040156]
 [-0.31265932  0.86418086 -0.02085696 -0.09320099 -1.1740861 ]
 [-0.41467157 -0.68059224 -0.11699343 -0.4384672   0.14537719]
 [-1.7982905   1.0423727   0.42576015 -0.65798914  2.103099  ]
 [ 0.5086817  -0.20136939 -0.27966458  1.5373868  -1.3815433 ]], shape=(5, 5), dtype=float32)
Truncated Normal Tensor:
 tf.Tensor(
[[-0.6383433  -1.149278   -0.8656428  -1.3332063  -0.17588058]
 [-0.38973865  0.77889794 -0.0948676   0.03605896 -0.07398779]
 [ 1.449635   -1.2038275   0.18531859 -0.14270774  0.58775544]
 [ 0.5645337   0.22553253 -1.6796802  -0.8548349   0.8119257 ]
 [-0.43062916  0.3560336   0.8046876  -1.0938212  -0.12828766]], shape=(5, 5), dtype=float32)
Hadamard Product:
 tf.Tensor(
[[ 5. 12.]
 [21. 32.]], shape=(2, 2), dtype=float32)


In [42]:
# Matrix multiplication with higher dimensions
mat_C = tf.random.uniform((4, 4), minval=0, maxval=10, dtype=tf.float32)
mat_D = tf.random.uniform((4, 4), minval=0, maxval=10, dtype=tf.float32)
mat_mul_high = tf.matmul(mat_C, mat_D)
print("High Dim Matrix Multiplication:\n", mat_mul_high)

High Dim Matrix Multiplication:
 tf.Tensor(
[[ 75.81592  105.19215   68.89405   86.360016]
 [ 25.82193  100.23475   45.258633  60.11636 ]
 [ 43.20284   99.20391   23.97472   68.41944 ]
 [ 42.99449   85.89349   69.86856   60.862537]], shape=(4, 4), dtype=float32)


In [43]:
# Transposing a higher-dimensional matrix
transposed_high = tf.transpose(batch_A, perm=[0, 2, 1])
print("High Dim Transpose:\n", transposed_high)

# Computing inverse of a matrix
matrix_inv_high = tf.linalg.inv(mat_C)
print("High Dim Inverse:\n", matrix_inv_high)

# Computing matrix determinant
matrix_det_high = tf.linalg.det(mat_C)
print("High Dim Determinant:", matrix_det_high)


High Dim Transpose:
 tf.Tensor(
[[[0.12615311 0.5461836  0.3076812 ]
  [0.5727513  0.7205157  0.48171103]
  [0.2993133  0.7889533  0.6537752 ]]

 [[0.12099254 0.22695613 0.28618944]
  [0.36291742 0.52010036 0.49184704]
  [0.24489999 0.86846626 0.6749884 ]]], shape=(2, 3, 3), dtype=float32)
High Dim Inverse:
 tf.Tensor(
[[ 0.07875811  0.01328545  0.07137002 -0.1012265 ]
 [-0.31158024 -0.50408274  0.28193605  0.6539258 ]
 [ 1.8993827   2.5278964  -2.0670362  -2.7803895 ]
 [-2.620956   -3.2132468   2.8082082   3.7483547 ]], shape=(4, 4), dtype=float32)
High Dim Determinant: tf.Tensor(83.28789, shape=(), dtype=float32)


In [44]:
# Computing Log Determinant
log_det_high = tf.linalg.logdet(mat_C)
print("High Dim Log Determinant:", log_det_high)

# Computing cosine similarity between two vectors
vector_A = tf.random.uniform((5,), minval=0, maxval=10, dtype=tf.float32)
vector_B = tf.random.uniform((5,), minval=0, maxval=10, dtype=tf.float32)
cosine_sim_high = tf.tensordot(vector_A, vector_B, axes=1) / (tf.norm(vector_A) * tf.norm(vector_B))
print("Cosine Similarity High:", cosine_sim_high)



High Dim Log Determinant: tf.Tensor(nan, shape=(), dtype=float32)
Cosine Similarity High: tf.Tensor(0.62366056, shape=(), dtype=float32)


In [45]:
# Computing element-wise logarithm
log_tensor_high = tf.math.log(mat_C + 1)
print("Log Tensor High:\n", log_tensor_high)

# Applying ReLU activation
relu_tensor_high = tf.nn.relu(tf.constant([-5.0, 2.0, -3.0, 7.0]))
print("ReLU High Tensor:", relu_tensor_high)


Log Tensor High:
 tf.Tensor(
[[2.3664546  2.079989   1.1554588  0.50234365]
 [1.1562983  1.1301594  2.1056244  1.7988834 ]
 [2.1231058  0.5109461  1.5002159  1.2990046 ]
 [1.4133334  1.9733812  1.8074082  1.3984736 ]], shape=(4, 4), dtype=float32)
ReLU High Tensor: tf.Tensor([0. 2. 0. 7.], shape=(4,), dtype=float32)
